name       : gcdemu
version    : 3.2.0
release    : 3
source     :
    - https://sourceforge.net/projects/cdemu/files/gcdemu/gcdemu-3.2.0.tar.bz2 : 6cd6b6f22b329bf487f07189050d1750161ecf99a532ce3a85211809fe57a418
license    : GPL-2.0-or-later
component  : desktop
summary    : GUI client for CDemu daemon.
description: |
    This is gCDEmu, a Gtk3-based GUI for controlling CDEmu daemon. It is part of the
    userspace-cdemu suite, a free, GPL CD/DVD-ROM device emulator for linux.

    It provides a graphic interface that allows performing the key tasks related to
    controlling the CDEmu daemon, such as loading and unloading devices, displaying
    devices' status and retrieving/setting devices' debug masks.
rundeps    :
    - python3-gobject
    - cdemu-daemon
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
