name       : gcdemu
version    : 3.2.1
release    : 4
source     :
    - https://datapacket.dl.sourceforge.net/project/cdemu/gcdemu/gcdemu-3.2.1.tar.bz2 : aff033fb19b1e7f6c001780ccf7c54743de26113720c2526aa8c9fe216dcbe52
license    : GPL-2.0-or-later
component  : desktop
summary    : GUI client for CDemu daemon.
description: |
    This is gCDEmu, a Gtk3-based GUI for controlling CDEmu daemon. It is part of the
    userspace-cdemu suite, a free, GPL CD/DVD-ROM device emulator for linux.

    It provides a graphic interface that allows performing the key tasks related to
    controlling the CDEmu daemon, such as loading and unloading devices, displaying
    devices' status and retrieving/setting devices' debug masks.
rundeps    :
    - python3-gobject
    - cdemu-daemon
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
